### ISSUE TITLE
Content-Type of the segments sometimes is not extracted

### ISSUE THREAD

**Issue by alexzubovsky** [davehorton/drachtio-sip#10]
https://github.com/davehorton/drachtio-sip/blob/75f5dac8d128ceb6bf04bf288f816a51c23fbdd9/lib/parser.js#L400

Content-type of the segments sometimes miss space after the column 
`Content-Type:application/sdp\r\n`
therefore the line 400
`const ct = /Content-Type:\s+(.*)\r\n/.exec(segments[i]) ;`
does not extract type. The fix is to allow 0 or more \s like
`const ct = /Content-Type:\s*(.*)\r\n/.exec(segments[i]) ;`

**Comment by davehorton** [comment]
You're saying that you are receiving a Content-Type header with no space after the colon?  That would be a bug on the sending side, would it not?

**Comment by alexzubovsky** [comment]
Not sure it would be proper to blame sending side - in https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html only key-word and colon are defined (in double quotes), but the spaces are not in the quotes:
```
4.17 Content-Type
The Content-Type entity-header field indicates the media type of the entity-body sent to the recipient or, in the case of the HEAD method, the media type that would have been sent had the request been a GET.

       Content-Type   = "Content-Type" ":" media-type
Media types are defined in section 3.7....
```
In our case, Content-Type and other headers of the request are ":<space>" separated, but the headers of the segments in the multipart are not. Moreover, some sources send perfectly (from the perspective of your parser.js) requests, but some put `Content-Type:application/sdp` into segment while others put the same space-less type in the meta segment (`application/rs-metadata+xml`)

**Comment by davehorton** [comment]
If you'd like to send me a PR feel free
